CarbWebClient/Controllers/BookingController.cs
using ServiceStack.ServiceClient.Web;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web.Requests;

namespace CarbWebClient.Controllers
{
    public class BookingController : Controller
    {
        // GET: Booking
        public ActionResult SearchBookings()
        {
            return View();
        }

        // GET: Booking/Details/5
        public ActionResult ViewBookings(int id)
        {
            JsonServiceClient client = new JsonServiceClient(ConfigurationManager.AppSettings["Client"]);

            var bookings = client.Get(new BookingRequest { Id = id });
            return View(bookings.Result);
        }

        // GET: Booking/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Booking/Create
        [HttpPost]
        public ActionResult CreateBooking(string date, string time, int noOfPeople, int cafeID)
        {
            JsonServiceClient client = new JsonServiceClient(ConfigurationManager.AppSettings["Client"]);
            DateTime startDate = Convert.ToDateTime(date + " " + time);
            //int cafeID = ViewBag.CafeID;
            int userID = 1;
            try
            {
                var bookingColl = client.Post(new BookingRequest
                {
                    CafeId = cafeID,
                    UserId = userID,
                    NoOfPeople = noOfPeople,
                    StartDate = startDate
                });

                ViewBag.Date = date;
                ViewBag.People = noOfPeople;
                ViewBag.Time = time;

                return View();

            }
            catch (Exception)
            {
                ViewBag.Error = "Der er ingen ledige borde på valgte tidspunkt!";
                ViewBag.CafeID = cafeID;
                return View();
            }
        }

        public ActionResult DeleteBooking()
        {
            return View();
        }

        public ActionResult DeleteBookingConfirmation(int id)
        {
            JsonServiceClient client = new JsonServiceClient(ConfigurationManager.AppSettings["Client"]);
            client.Delete(new DeleteBookingRequest { Id = id });
            ViewBag.Delete = id;

            return View();
        }

        // GET: Booking/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Booking/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Booking/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Booking/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

CarbWebClient/Controllers/CafeController.cs
using ServiceStack.ServiceClient.Web;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web.Requests;

namespace CarbWebClient.Controllers
{
    public class CafeController : Controller
    {
        // GET: Cafe
        public ActionResult Index()
        {
            return View();
        }

        // GET: Cafe/Details/5
        public ActionResult ViewCafe(int id)
        {
            JsonServiceClient client = new JsonServiceClient(ConfigurationManager.AppSettings["Client"]);
            var cafeColl = client.Get(new CafeRequest { Id = id });
            return View(cafeColl.Result);
        }

        // GET: Cafe/Create
        public ActionResult Create()
        {
            return View();
        }
        public ActionResult SearchZip(string Search)
        {
            JsonServiceClient client = new JsonServiceClient(ConfigurationManager.AppSettings["Client"]);
            var cafes = client.Get(new GetCafeByZipRequest { Zip = Search });
            return View(cafes.Result);
        }
        public ActionResult ViewCafeError(int cafeID)
        {
            ViewBag.ErrorBooking = "Der skete en fejl under bookning";
            return View("ViewCafe/" + cafeID);
        }
        // POST: Cafe/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Cafe/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Cafe/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Cafe/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Cafe/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

CarbWebClient/Views/Booking/CreateBooking.cshtml
@model Model.Booking


@{
    if (ViewBag.Error != null)
    {
        <meta http-equiv="refresh" content="3;url=/Cafe/ViewCafe/@ViewBag.CafeID" />
        <div class="col-4">
            <h2>
                @ViewBag.Error
            </h2>
            <h4>
                @Html.ActionLink("Tilbage", "ViewCafe", "Cafe", new { id = ViewBag.CafeID })
            </h4>
            <h3></h3>
        </div>
    }
    else
    {
        <div class="col-4">
            <h2>
                Tak for din bestilling d. @ViewBag.Date kl. @ViewBag.Time!
            </h2>
            <h4>
                @Html.ActionLink("Home", "Index", "Home")
            </h4>
            <h3></h3>
        </div>
    }
}

CarbWebClient/Views/Booking/DeleteBooking.cshtml
@model Model.Booking

<!DOCTYPE html>

<div class="row">
    <div class="col-md-4">
        <h2>
            Slet Booking
        </h2>
        <p>
            BookingID:
            @using (Html.BeginForm("DeleteBookingConfirmation", "Home", FormMethod.Get))
            {
                @Html.TextBox("Id") <input type="submit" value="Slet" />
            }
        </p>

    </div>
</div>

CarbWebClient/Views/Booking/DeleteBookingConfirmation.cshtml
@model Model.Booking

<!DOCTYPE html>

<div class="col-4">
<h2>
    Booking med ID: @ViewBag.Delete er slettet!
</h2>
<h4>
    @Html.ActionLink("Tilbage", "Index", "Home")
</h4>
<h3></h3>
</div>

CarbWebClient/Views/Booking/Details.cshtml
@model Web.Requests.BookingRequest

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>BookingRequest</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NoOfPeople)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NoOfPeople)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CafeId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CafeId)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CarbWebClient/Views/Booking/Edit.cshtml
@model Web.Requests.BookingRequest

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>BookingRequest</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NoOfPeople, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NoOfPeople, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NoOfPeople, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CafeId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CafeId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CafeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CarbWebClient/Views/Booking/SearchBookings.cshtml
@{
    ViewBag.Title = "SearchBookings";
}

<h2>SearchBookings</h2>
@using (Html.BeginForm("ViewBookings", "Booking", FormMethod.Get))
{
    @Html.TextBox("id") <input type="submit" value="Search" />
}

CarbWebClient/Views/Booking/ViewBookings.cshtml
@model IEnumerable<Model.Booking>

@{
    ViewBag.Title = "ViewBookings";
}

<h2>ViewBookings</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.StartDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.User.Id)
        </th>
        <th>

        </th>
        <th>
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.StartDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.User.Id)
        </td>
        <td>
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Id)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>